# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_UD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
